# Generated by Django 4.1.1 on 2022-10-01 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('body_q', models.TextField(max_length=200)),
                ('image_q', models.ImageField(upload_to='')),
                ('opt1', models.TextField()),
                ('opt2', models.TextField()),
                ('opt3', models.TextField()),
                ('opt4', models.TextField()),
                ('image_of_quetionop1', models.ImageField(upload_to='')),
                ('image_of_quetionop2', models.ImageField(upload_to='')),
                ('image_of_quetionop3', models.ImageField(upload_to='')),
                ('image_of_quetionop4', models.ImageField(upload_to='')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.datetime.fromtimestamp)),
            ],
        ),
    ]
