# Generated by Django 4.1.1 on 2022-10-02 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuesPy', '0004_alter_question_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('qnfile', models.FileField(upload_to='')),
                ('op1file', models.FileField(upload_to='')),
                ('op2file', models.FileField(upload_to='')),
                ('op3file', models.FileField(upload_to='')),
                ('op4file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 2, 23, 46, 38, 18657)),
        ),
    ]
