# Generated by Django 4.1.1 on 2022-10-02 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuesPy', '0008_alter_question_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='file_upload',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 3, 2, 8, 3, 258090)),
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 10, 3, 2, 8, 3, 210134)),
        ),
    ]
